# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
